export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const REQUEST_LOAN = 'REQUEST_LOAN';
export const GET_ALL_LOAN_REQUEST = 'GET_ALL_LOAN_REQUEST';
export const SUBMIT_LOAN_REQUEST = 'SUBMIT_LOAN_REQUEST';
